''' IK2220 SDN Phase 1 Topology Configuration '''

TOPOLOGY = [
    {
        'name':'h1',
        'type':'HOST',
        'ip':'100.0.0.11/24',
    },
    {
        'name':'h2',
        'type':'HOST',
        'ip':'100.0.0.12/24',
    },
    {
        'name':'ds1',
        'type':'HOST',
        'ip':'100.0.0.20/24',
    },
    {
        'name':'ds2',
        'type':'HOST',
        'ip':'100.0.0.21/24',
    },
    {
        'name':'ds3',
        'type':'HOST',
        'ip':'100.0.0.22/24'
    },
    {
        'name':'ws1',
        'type':'HOST',
        'ip':'100.0.0.40/24'
    },
    {
        'name':'ws2',
        'type':'HOST',
        'ip':'100.0.0.41/24'
    },
    {
        'name':'ws3',
        'type':'HOST',
        'ip':'100.0.0.42/24'
    },
    {
        'name':'h3',
        'type':'HOST',
        'ip':'100.0.0.51/24'
    },
    {
        'name':'h4',
        'type':'HOST',
        'ip':'100.0.0.52/24'
    },
    {
        'name':'insp',
        'type':'HOST',
        'ip':'100.0.0.30/24'
    },
    {
        'name':'sw1',
        'type':'SWITCH',
        'links':{
            'h1',
            'h2',
            'fw1',
        }
    },
    {
        'name':'sw2',
        'type':'SWITCH',
        'links':{
            'fw1',
            'fw2',
            'lb1',
            'ids',
        }
    },
    {
        'name':'sw3',
        'type':'SWITCH',
        'links':{
            'ds1',
            'ds2',
            'ds3',
            'lb1',
        }
    },
    {
        'name':'sw4',
        'type':'SWITCH',
        'links':{
            'ws1',
            'ws2',
            'ws3',
            'lb2',
        }
    },
    {
        'name':'sw5',
        'type':'SWITCH',
        'links':{
            'h3',
            'h4',
            'napt',
        }
    },
    {
        'name':'fw1',
        'type':'SWITCH',
        'links':{
            'sw1',
            'sw2',
        }
    },
    {
        'name':'fw2',
        'type':'SWITCH',
        'links':{
            'napt',
            'sw2',
        }
    },
    {
        'name':'lb1',
        'type':'SWITCH',
        'links':{
            'sw2',
            'sw3',
        }
    },
    {
        'name':'lb2',
        'type':'SWITCH',
        'links':{
            'ids',
            'sw4',
        }
    },
    {
        'name':'napt',
        'type':'SWITCH',
        'links':{
            'fw2',
            'sw5',
        }
    },
    {
        'name':'ids',
        'type':'SWITCH',
        'links':{
            'sw2',
            'insp',
            'fw2',
        }
    },
]
